### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by fimreal** [Ericwyn/Andex#3]
macos [go1.16.6 darwin/amd64] 编译后运行会报错：
```
[Andex-INFO] [0906-084429] DEBUG 模式已打开
[Andex-INFO] [0906-084429] can't find .conf/ path for save db and config
[xorm] [info]  2021/09/06 08:44:29.769851 [SQL] SELECT name FROM sqlite_master WHERE type='table' [] - 1.314727ms
unable to open database file: no such file or directory
[Andex-ERR ] [0906-084429] SYNC TABLE ERROR!!
```
手动创建 .conf 目录后，执行报错：
```
[Andex-ERR ] [0906-091027] create .conf/ dir fail
[Andex-INFO] [0906-091027] ==================== 启动配置 Start ====================
[Andex-INFO] [0906-091027] 首次创建 sys conf
[Andex-INFO] [0906-091027] 服务运行端口:8080
用户配置文件已更新
[Andex-INFO] [0906-091028] 运行配置载入完毕
[Andex-INFO] [0906-091028] token 过期时间设置:5400
[Andex-INFO] [0906-091028] 距离上次 token 获取时间已过去:0
[Andex-INFO] [0906-091028]
[Andex-INFO] [0906-091028] 检查 RootPath 设置:/
[Andex-INFO] [0906-091028] 验证文件夹路径:
[Andex-INFO] [0906-091028] 文件夹路径验证成功, FileId:root
[Andex-DBUG] [0906-091028] 无法从已有 pathMap 缓存当中找到根目录 FileId 设置
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x433193b]

goroutine 1 [running]:
github.com/Ericwyn/GoTools/file.OpenFile(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/xxx/go/pkg/mod/github.com/!ericwyn/!go!tools@v0.0.0-20210121122108-55fad04a172d/file/oop.go:55 +0x17b
github.com/Ericwyn/Andex/service.LoadReadmeFile()
	/Users/xxx/tmp/code/Andex/service/conf.go:124 +0x4c
main.loadConfig()
	/Users/xxx/tmp/code/Andex/Andex.go:99 +0x3ba
main.main()
	/Users/xxx/tmp/code/Andex/Andex.go:35 +0xad
```
看起来在 macos 环境没办法创建目录。

下载打包好的二进制包 linux64.zip，在 linux 环境执行运行报错：
```
[Andex-INFO] [0906-090142] DEBUG 模式已打开
[Andex-ERR ] [0906-090142] create .conf/ dir fail
[xorm] [info]  2021/09/06 09:01:42.126102 [SQL] SELECT name FROM sqlite_master WHERE type='table' [] - 328.398µs
[xorm] [info]  2021/09/06 09:01:42.126225 [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [andex_path] - 16.861µs
[xorm] [info]  2021/09/06 09:01:42.126361 [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [andex_path] - 13.725µs
[xorm] [info]  2021/09/06 09:01:42.126451 [SQL] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [andex_config] - 12.383µs
[xorm] [info]  2021/09/06 09:01:42.126548 [SQL] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [andex_config] - 12.844µs
[Andex-INFO] [0906-090142] ==================== 启动配置 Start ====================
[xorm] [info]  2021/09/06 09:01:42.126781 [SQL] SELECT `key`, `value` FROM `andex_config` WHERE `key`=? LIMIT 1 [refreshToken] - 17.522µs
[xorm] [info]  2021/09/06 09:01:42.126898 [SQL] SELECT `key`, `value` FROM `andex_config` WHERE `key`=? LIMIT 1 [authorization] - 25.067µs
[xorm] [info]  2021/09/06 09:01:42.126991 [SQL] SELECT `key`, `value` FROM `andex_config` WHERE `key`=? LIMIT 1 [driveID] - 14.097µs
[xorm] [info]  2021/09/06 09:01:42.127084 [SQL] SELECT `key`, `value` FROM `andex_config` WHERE `key`=? LIMIT 1 [rootPath] - 19.417µs
[xorm] [info]  2021/09/06 09:01:42.127175 [SQL] SELECT `key`, `value` FROM `andex_config` WHERE `key`=? LIMIT 1 [lastGetTokenTime] - 11.381µs
[Andex-INFO] [0906-090142] 服务运行端口:8080
[Andex-INFO] [0906-090142] 从数据库中载入 Authorization
[Andex-INFO] [0906-090142] 运行配置载入完毕
[Andex-INFO] [0906-090142] token 过期时间设置:5400
[Andex-INFO] [0906-090142] 距离上次 token 获取时间已过去:254
[Andex-INFO] [0906-090142]
[Andex-INFO] [0906-090142] 检查 RootPath 设置:/
[Andex-INFO] [0906-090142] 验证文件夹路径:
[Andex-INFO] [0906-090142] 文件夹路径验证成功, FileId:root
[xorm] [info]  2021/09/06 09:01:42.127529 [SQL] SELECT `path`, `name`, `file_id`, `is_dir`, `password` FROM `andex_path` [] - 14.668µs
[Andex-DBUG] [0906-090142] 旧 Root Path -> FileId:root
[Andex-DBUG] [0906-090142] 旧 Root Path -> FileId:root
[Andex-DBUG] [0906-090142] rootPath 设置未变更
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x73b7bb]

goroutine 1 [running]:
github.com/Ericwyn/GoTools/file.OpenFile(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ericwyn/go/pkg/mod/github.com/!ericwyn/!go!tools@v0.0.0-20210121122108-55fad04a172d/file/oop.go:55 +0x17b
github.com/Ericwyn/Andex/service.LoadReadmeFile()
	/mnt/d/Chaos/go/Andex/service/conf.go:124 +0x4c
main.loadConfig()
	/mnt/d/Chaos/go/Andex/Andex.go:99 +0x3ba
main.main()
	/mnt/d/Chaos/go/Andex/Andex.go:35 +0xad
```
Linux 可以正常创建目录，后面报错类似前面。报错在读取 README.md 文件：
https://github.com/Ericwyn/Andex/blob/bda0a47b6e7d1fea40a92f5997918f0b18885254/service/conf.go#L124

问题时间 2021.09.06，都是最新 release

**Comment by Ericwyn** [comment]
感谢您的反馈，您有尝试过试过运行目录下创建一个 README.md 文件之后再启动么？
